<script type="text/javascript">
//<![CDATA[
    /* Set default country (Optional) */
    $('billing:country_id').value = 'GB';
    billingRegionUpdater.update();
        
    $('shipping:country_id').value = 'GB';
    shippingRegionUpdater.update();
    
    /* Initialise the postcode object */
    var meanbee_postcode_billing = new OPCPostcode('<?php echo Mage::getBaseUrl() ?>', 'billing');
    var meanbee_postcode_shipping = new OPCPostcode('<?php echo Mage::getBaseUrl() ?>', 'shipping');
//]]>
</script>
