<script type="text/javascript">
//<![CDATA[

    var MEANBEE_POSTCODE_BASE_URL = '<?php echo Mage::getBaseUrl() ?>';

    if(window.location.href.match('https://') && !MEANBEE_POSTCODE_BASE_URL.match('https://')){
        MEANBEE_POSTCODE_BASE_URL = MEANBEE_POSTCODE_BASE_URL.replace('http://', 'https://')
    }

    /* Set default country (Optional) */
    $('billing:country_id').value = 'GB';
    billingRegionUpdater.update();
        
    $('shipping:country_id').value = 'GB';
    shippingRegionUpdater.update();
    
    /* Initialise the postcode object */
    var meanbee_postcode_billing = new OPCPostcode('billing');
    var meanbee_postcode_shipping = new OPCPostcode('shipping');
//]]>
</script>
